### ISSUE TITLE
Unable to run it locally

### ISSUE THREAD

**Issue by iit2011081** [tellform/tellform#162]
Done both the steps 
npm install
bower install
but when I run grunt build it gave me following error.
Loading "gruntfile.js" tasks...ERROR
>> Error: Bower components directory does not exist at /var/www/tellform/public/lib
Warning: Task "build" not found. Use --force to continue.
Aborted due to warnings.

and then I run  node ./scripts/setup.js. It also gave me error
module.js:328
    throw err;
    ^

Error: Cannot find module 'bcrypt'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/www/tellform/node_modules/mongoose-utilities/lib/basicAuth.js:11:14)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at /var/www/tellform/node_modules/mongoose-utilities/index.js:11:26
    at Array.forEach (native)
    at Object.<anonymous> (/var/www/tellform/node_modules/mongoose-utilities/index.js:8:48)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/www/tellform/app/models/form.server.model.js:11:15)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at /var/www/tellform/config/express.js:50:3
    at Array.forEach (native)
    at module.exports (/var/www/tellform/config/express.js:49:49)
    at Object.<anonymous> (/var/www/tellform/scripts/setup.js:29:39)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by whitef0x0** [comment]
@iit2011081 what version of NodeJS and NPM are you running. 

Also on what OS?

**Comment by iit2011081** [comment]
Now some how I am able to run it but it get crashed every time when I create a new field in a form.
 Segmentation fault (core dumped)
 [nodemon] app crashed - waiting for file changes before starting...

**Comment by whitef0x0** [comment]
@iit2011081 see this for details on fixing it https://github.com/nodejs/node/issues/2763.

**Comment by whitef0x0** [comment]
What version of Node/NPM are you running?

**Comment by whitef0x0** [comment]
Closing this issue due to inactivity.
