### ISSUE TITLE
Installation fails at `npm install`

### ISSUE THREAD

**Issue by vaMuchenje** [tellform/tellform#200]
#### What's this issue about?

The installation instructions are resulting in an error message. When I try to install dependencies with:
`npm install` I get an error message.

#### Expected behavior

It was supposed to install the dependencies normally.

#### Actual behavior

An error message is returned: 
```
...
make: Leaving directory '/home/tendi/tellform/node_modules/v8-debug/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Linux 4.10.1-041001-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/tendi/tellform/node_modules/v8-debug/build/debug/v0.7.7/node-v57-linux-x64/debug.node" "--module_name=debug" "--module_path=/home/tendi/tellform/node_modules/v8-debug/build/debug/v0.7.7/node-v57-linux-x64"
gyp ERR! cwd /home/tendi/tellform/node_modules/v8-debug
gyp ERR! node -v v8.1.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/tendi/tellform/node_modules/v8-debug/build/debug/v0.7.7/node-v57-linux-x64/debug.node --module_name=debug --module_path=/home/tendi/tellform/node_modules/v8-debug/build/debug/v0.7.7/node-v57-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/tendi/tellform/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:125:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:897:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
node-pre-gyp ERR! System Linux 4.10.1-041001-generic
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/tendi/tellform/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/tendi/tellform/node_modules/v8-debug
node-pre-gyp ERR! node -v v8.1.4
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/tendi/tellform/node_modules/v8-debug/build/debug/v0.7.7/node-v57-linux-x64/debug.node --module_name=debug --module_path=/home/tendi/tellform/node_modules/v8-debug/build/debug/v0.7.7/node-v57-linux-x64' (1)
npm WARN The package grunt-contrib-uglify is included as both a dev and production dependency.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v8-debug@0.7.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-debug@0.7.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tendi/.npm/_logs/2017-07-16T21_14_44_751Z-debug.log

```

#### Steps to reproduce

Just run `npm install`

#### Environment

I have Ubuntu 17.04, and the latest version of Node and npm. i.e. 8.1.4 and 5.3.0 respectively.

**Comment by whitef0x0** [comment]
@vaMuchenje it won't work with the latest version of nodeJS. See package.json for the compatible version.
