### ISSUE TITLE
Couldn't complete registration due to errors: Path `username` is required.

### ISSUE THREAD

**Issue by h133gqa** [tellform/tellform#202]
#### What's this issue about?
User-reg failed

> Couldn't complete registration due to errors:
> Path `username` is required.

```
(node:51) DeprecationWarning: crypto.pbkdf2 without specifying a digest is deprecated. Please specify a digest
    Error: 
    { ValidationError: temporary_users validation failed
        at MongooseError.ValidationError (/opt/tellform/node_modules/mongoose/lib/error/validation.js:22:11)
        at model.Document.invalidate (/opt/tellform/node_modules/mongoose/lib/document.js:1380:32)
        at /opt/tellform/node_modules/mongoose/lib/document.js:1256:17
        at validate (/opt/tellform/node_modules/mongoose/lib/schematype.js:702:7)
        at /opt/tellform/node_modules/mongoose/lib/schematype.js:733:9
        at Array.forEach (native)
        at SchemaString.SchemaType.doValidate (/opt/tellform/node_modules/mongoose/lib/schematype.js:707:19)
        at /opt/tellform/node_modules/mongoose/lib/document.js:1254:9
        at _combinedTickCallback (internal/process/next_tick.js:67:7)
        at process._tickDomainCallback (internal/process/next_tick.js:122:9)
      message: 'temporary_users validation failed',
      name: 'ValidationError',
      errors: 
       { username: 
          { ValidatorError: Path `username` is required.
              at MongooseError.ValidatorError (/opt/tellform/node_modules/mongoose/lib/error/validator.js:25:11)
              at validate (/opt/tellform/node_modules/mongoose/lib/schematype.js:701:13)
              at /opt/tellform/node_modules/mongoose/lib/schematype.js:733:9
              at Array.forEach (native)
              at SchemaString.SchemaType.doValidate (/opt/tellform/node_modules/mongoose/lib/schematype.js:707:19)
              at /opt/tellform/node_modules/mongoose/lib/document.js:1254:9
              at _combinedTickCallback (internal/process/next_tick.js:67:7)
              at process._tickDomainCallback (internal/process/next_tick.js:122:9)
            message: 'Path `username` is required.',
            name: 'ValidatorError',
            properties: [Object],
            kind: 'required',
            path: 'username',
            value: undefined } } }
```

#### Expected behavior
Finish user registration

#### Actual behavior
> Couldn't complete registration due to errors:
> Path `username` is required.

#### Steps to reproduce
We don't use localhost, because we wanted to test on servers. We adapted the docker run "BASE_URL=localhost" with our used URL. 

#### Environment
Docker on Ubuntu 16.04 LTS

**Comment by whitef0x0** [comment]
@h133gqa Just to clarify, you are getting this error after submitting signup in the web app?

**Comment by whitef0x0** [comment]
@h133gqa this has been fixed

**Comment by h133gqa** [comment]
thx, will try!

**Comment by eduoda** [comment]
I got the same error using the current docker image. I take a look at the singup request, it doesn't send the username parameter.
