### ISSUE TITLE
Forked master branch, unable to sign up for new account when Docker ran locally

### ISSUE THREAD

**Issue by leonardloo** [tellform/tellform#208]
I forked the master branch, built the image locally: `docker build -t tellform -f ./Dockerfile .` then ran it like so:

```
docker run -p 27017:27017 -d --name some-mongo mongo
docker run -p 127.0.0.1:6379:6379 -d --name some-redis redis
docker run --rm -p 3000:3000 --link some-redis:redis-db --link some-mongo:db -e "SUBDOMAINS_DISABLED=TRUE" -e "DISABLE_CLUSTER_MODE=TRUE" -e "MAILER_EMAIL_ID=<YourEmailAPI_ID>" -e "MAILER_FROM=<noreply@yourdomain.com>" -e "MAILER_SERVICE_PROVIDER=<YourEmailAPIProvider>"  -e "MAILER_PASSWORD=<YourAPIKey>" -e "BASE_URL=localhost" -p 80:80 tellform
```

I ended up getting this error when I try to sign up a new account:
```
    TypeError: Cannot read property 'code' of null
        at Object.exports.getErrorMessage (/opt/tellform/app/controllers/errors.server.controller.js:26:9)
        at /opt/tellform/app/controllers/users/users.authentication.server.controller.js:122:29
        at SMTPConnection.<anonymous> (/opt/tellform/node_modules/nodemailer-smtp-transport/src/smtp-transport.js:106:16)
        at SMTPConnection.g (events.js:292:16)
        at emitOne (events.js:96:13)
        at SMTPConnection.emit (events.js:188:7)
        at SMTPConnection._onError (/opt/tellform/node_modules/smtp-connection/src/smtp-connection.js:374:10)
        at emitOne (events.js:96:13)
        at Socket.emit (events.js:188:7)
        at emitErrorNT (net.js:1277:8)
        at _combinedTickCallback (internal/process/next_tick.js:80:11)
        at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

Why is that the case?

**Comment by leonardloo** [comment]
Also, should I change the `ENV BASE_URL` in the Dockerfile from `tellform.dev` to `localhost`?

**Comment by whitef0x0** [comment]
@leonardo your .env file should have (as a bare minimum)

BASE_URL
MAILER_EMAIL_ID
MAILER_FROM
MAILER_PASSWORD
