### ISSUE TITLE
Failed to create user account

### ISSUE THREAD

**Issue by VerHext** [tellform/tellform#251]
#### What's this issue about?
I try in my install version via docker to create a user account. If this fails due to the following error message:

```

    Error:
    { ValidationError: temporary_users validation failed
        at MongooseError.ValidationError (/opt/tellform/node_modules/mongoose/lib/error/validation.js:22:11)
        at model.Document.invalidate (/opt/tellform/node_modules/mongoose/lib/document.js:1380:32)
        at /opt/tellform/node_modules/mongoose/lib/document.js:1256:17
        at validate (/opt/tellform/node_modules/mongoose/lib/schematype.js:702:7)
        at /opt/tellform/node_modules/mongoose/lib/schematype.js:733:9
        at Array.forEach (native)
        at SchemaString.SchemaType.doValidate (/opt/tellform/node_modules/mongoose/lib/schematype.js:707:19)
        at /opt/tellform/node_modules/mongoose/lib/document.js:1254:9
        at _combinedTickCallback (internal/process/next_tick.js:67:7)
        at process._tickDomainCallback (internal/process/next_tick.js:122:9)
      message: 'temporary_users validation failed',
      name: 'ValidationError',
      errors:
       { username:
          { ValidatorError: Path `username` is required.
              at MongooseError.ValidatorError (/opt/tellform/node_modules/mongoose/lib/error/validator.js:25:11)
              at validate (/opt/tellform/node_modules/mongoose/lib/schematype.js:701:13)
              at /opt/tellform/node_modules/mongoose/lib/schematype.js:733:9
              at Array.forEach (native)
              at SchemaString.SchemaType.doValidate (/opt/tellform/node_modules/mongoose/lib/schematype.js:707:19)
              at /opt/tellform/node_modules/mongoose/lib/document.js:1254:9
              at _combinedTickCallback (internal/process/next_tick.js:67:7)
              at process._tickDomainCallback (internal/process/next_tick.js:122:9)
            message: 'Path `username` is required.',
            name: 'ValidatorError',
            properties: [Object],
            kind: 'required',
            path: 'username',
            value: undefined } } }
    POST /auth/signup 400 358.583 ms - 42
     { ValidatorError: Path `username` is required.

    Error:
    { ValidationError: temporary_users validation failed
        at MongooseError.ValidationError (/opt/tellform/node_modules/mongoose/lib/error/validation.js:22:11)
        at model.Document.invalidate (/opt/tellform/node_modules/mongoose/lib/document.js:1380:32)
        at /opt/tellform/node_modules/mongoose/lib/document.js:1256:17
        at validate (/opt/tellform/node_modules/mongoose/lib/schematype.js:702:7)
        at /opt/tellform/node_modules/mongoose/lib/schematype.js:733:9
        at Array.forEach (native)
        at SchemaString.SchemaType.doValidate (/opt/tellform/node_modules/mongoose/lib/schematype.js:707:19)
        at /opt/tellform/node_modules/mongoose/lib/document.js:1254:9
        at _combinedTickCallback (internal/process/next_tick.js:67:7)
        at process._tickDomainCallback (internal/process/next_tick.js:122:9)
      message: 'temporary_users validation failed',
      name: 'ValidationError',
      errors:
       { username:
          { ValidatorError: Path `username` is required.
              at MongooseError.ValidatorError (/opt/tellform/node_modules/mongoose/lib/error/validator.js:25:11)
              at validate (/opt/tellform/node_modules/mongoose/lib/schematype.js:701:13)
              at /opt/tellform/node_modules/mongoose/lib/schematype.js:733:9
              at Array.forEach (native)
              at SchemaString.SchemaType.doValidate (/opt/tellform/node_modules/mongoose/lib/schematype.js:707:19)
              at /opt/tellform/node_modules/mongoose/lib/document.js:1254:9
              at _combinedTickCallback (internal/process/next_tick.js:67:7)
              at process._tickDomainCallback (internal/process/next_tick.js:122:9)
            message: 'Path `username` is required.',
            name: 'ValidatorError',
            properties: [Object],
            kind: 'required',
            path: 'username',
            value: undefined } } }
    POST /auth/signup 400 358.583 ms - 42

```
#### Expected behavior
I wanted to enter a user account in the db. :)

#### Steps to reproduce
Create a user account via web panal...

#### Environment
I use this on Ubuntu 16.04 with the docker container from https://tellform.com/install_docker

**Comment by whitef0x0** [comment]
@VerHext I've updated the docker installation instructions that now use docker-compose. Try it out and let me know if you have any problems with it.
