### ISSUE TITLE
Installation fails at `node ./scripts/setup.js`

### ISSUE THREAD

**Issue by digitalronin** [tellform/tellform#256]
#### What's this issue about?

Installing from scratch, the installation fails when trying to run `node ./scripts/setup.js`

I could get a bit further by setting the env vars manually, and fixing a couple of errors with the `gruntfile.js` (commenting out the linter and changing `--debug` to `--inspect` for the node parameters), but I thought I should raise this as an issue so that it can be fixed.

#### Expected behavior

The installation instructions say I should run `node ./scripts/setup.js` to create my user account. So, I assume there should be a series of interactive prompts to help me do this.

#### Actual behavior

I got the following error;

```
$ node ./scripts/setup.js                                 
module.js:529
    throw err;
    ^

Error: Cannot find module 'envfile'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/davidsalgado/code/form-builder/tellform/scripts/setup.js:11:12)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:201:16)
    at bootstrap_node.js:626:3
```

I also tried running `npm i -g envfile` and then trying again, but it didn't make any difference.

#### Steps to reproduce

Work through the installation instructions from scratch;

```
$ git clone git@github.com:tellform/tellform.git
$ cd tellform/
$ npm i
$ npm i -g bower
$ bower install
$ node ./scripts/setup.js
```

#### Environment

Mac OSX 10.11.6
node 8.5.0
bower 1.8.2
npm 5.3.0

**Comment by whitef0x0** [comment]
@digitalronin This PR https://github.com/tellform/tellform/pull/257 fixes the issue
