### ISSUE TITLE
JS error when running in Docker container

### ISSUE THREAD

**Issue by dshepherd** [tellform/tellform#277]
#### What's this issue about?
When running in the docker container, I get "__ is not a function" error in /opt/tellform/app/views/500.server.view.pug:6

#### Expected behavior
Expected page load

#### Actual behavior
tellform_1  | TypeError: /opt/tellform/app/views/500.server.view.pug:6
tellform_1  |     4|     section.public-form.auth.sigin-view.valign-wrapper
tellform_1  |     5|         div.row.valign
tellform_1  |   > 6|             h3.col-md-12.text-center=__('500_HEADER')
tellform_1  |     7|             div.col-md-4.col-md-offset-4
tellform_1  |     8|                 if process.env.NODE_ENV == 'development' || process.env.NODE_ENV == 'test'
tellform_1  |     9|                     div.col-md-12.text-center(style="padding-bottom: 50px;")
tellform_1  |
tellform_1  | __ is not a function
tellform_1  |     at eval (eval at wrap (/opt/tellform/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:133:57)
tellform_1  |     at template (eval at wrap (/opt/tellform/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:167:122)
tellform_1  |     at /opt/tellform/node_modules/consolidate/lib/consolidate.js:809:16
tellform_1  |     at /opt/tellform/node_modules/consolidate/lib/consolidate.js:144:5
tellform_1  |     at Promise._execute (/opt/tellform/node_modules/bluebird/js/release/debuggability.js:303:9)
tellform_1  |     at Promise._resolveFromExecutor (/opt/tellform/node_modules/bluebird/js/release/promise.js:483:18)
tellform_1  |     at new Promise (/opt/tellform/node_modules/bluebird/js/release/promise.js:79:10)
tellform_1  |     at promisify (/opt/tellform/node_modules/consolidate/lib/consolidate.js:137:10)
tellform_1  |     at View.exports.pug [as engine] (/opt/tellform/node_modules/consolidate/lib/consolidate.js:793:10)
tellform_1  |     at View.render (/opt/tellform/node_modules/express/lib/view.js:126:8)
tellform_1  |     at tryRender (/opt/tellform/node_modules/express/lib/application.js:639:10)
tellform_1  |     at EventEmitter.render (/opt/tellform/node_modules/express/lib/application.js:591:3)
tellform_1  |     at ServerResponse.render (/opt/tellform/node_modules/express/lib/response.js:961:7)
tellform_1  |     at /opt/tellform/config/express.js:326:19
tellform_1  |     at Layer.handle_error (/opt/tellform/node_modules/express/lib/router/layer.js:71:5)
tellform_1  |     at trim_prefix (/opt/tellform/node_modules/express/lib/router/index.js:310:13)
tellform_1  |     at /opt/tellform/node_modules/express/lib/router/index.js:280:7
tellform_1  |     at Function.process_params (/opt/tellform/node_modules/express/lib/router/index.js:330:12)
tellform_1  |     at next (/opt/tellform/node_modules/express/lib/router/index.js:271:10)
tellform_1  |     at /opt/tellform/node_modules/raven/lib/middleware/connect.js:22:13
tellform_1  |     at /opt/tellform/node_modules/raven/lib/client.js:143:15
tellform_1  |     at /opt/tellform/node_modules/raven/lib/parsers.js:45:9
tellform_1  |     at /opt/tellform/node_modules/raven/lib/utils.js:166:36
tellform_1  |     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:447:3)

#### Steps to reproduce
$ git clone https://github.com/tellform/docker_files 
$ cd docker_files
create .env file with below values
edit docker-compose.yml with port mappings (due to existing http/s service running)
$docker-compose up -d 

#### Environment
Debian Stretch
Docker version 17.09.1-ce, build 19e2cf6
docker-compose version 1.18.0, build 8dd22a9

#### docker-compose.yml
version: "3"
services:
  tellform:
    image: tellform/app:stable
    ports:
      - "5000"
      - 587:587
    env_file:
      - .env
    links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis
  redis:
    restart: always
    image: redis
    volumes:
      - "$ROOT/redis:/data"
    ports:
      - "63790:6379"
  web:
    image: tellform/nginx:stable
    restart: always
    ports:
      - "8080:80"
      - "4430:443"
      - "20523:20523"
    env_file:
      - .env
    volumes:
      - "$ROOT/certs:/certs"
  mongo:
    restart: always
    image: mongo
    volumes:
      - "$ROOT/mongo:/data"
    ports:
      - "27107:27107"

####.env values
ROOT=/home/dan.shepherd/tellformdata

NODE_ENV=development
SESSION_SECRET=test
BASE_URL=tellform.example.org:4430
PORT=5000
SOCKET_PORT=20523

MONGODB_URI=mongodb://mongo/tellform
REDIS_URL=redis://redis:6379

SUBDOMAINS_DISABLED=true
ENABLE_CLUSTER_MODE=false
MAILER_EMAIL_ID=me@example.org
MAILER_PASSWORD=mypassword
MAILER_FROM=me@example.org
MAILER_SERVICE_PROVIDER=Gmail

CREATE_ADMIN=true
ADMIN_EMAIL=me@example.org
ADMIN_USERNAME=admin
ADMIN_PASSWORD=admin

APP_NAME=Test
TLS_FLAVOR=cert

**Comment by Gomes81** [comment]
I have the same error here, running in docker... Does anyone knows the reason why this happens?
