### ISSUE TITLE
Problem with npm install (i18n-lint)

### ISSUE THREAD

**Issue by mojontwins** [tellform/tellform#311]
#### What's this issue about?

I get an error when executing npm install:
```
[    ..............] / fetchMetadata: sill removeObsoleteDep removing is@3.2.1 from the tree as its been replaced by a newer version or is no longer required
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t git://github.com/jwarby/i18n-lint.git
npm ERR!
npm ERR! undefined
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-10-01T09_14_13_044Z-debug.log
```
The log reads as follows:
```
[...]
114 silly saveTree └── wiredep@4.0.0
115 verbose stack Error: exited with error code: 128
115 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/pacote/lib/util/finished.js:12:19)
115 verbose stack     at emitTwo (events.js:106:13)
115 verbose stack     at ChildProcess.emit (events.js:191:7)
115 verbose stack     at maybeClose (internal/child_process.js:920:16)
115 verbose stack     at Socket.<anonymous> (internal/child_process.js:351:11)
115 verbose stack     at emitOne (events.js:96:13)
115 verbose stack     at Socket.emit (events.js:188:7)
115 verbose stack     at Pipe._handle.close [as _onclose] (net.js:509:12)
116 verbose cwd /root/survey_tests/tellform
117 verbose Linux 3.10.0-514.el7.x86_64
118 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
119 verbose node v6.14.4
120 verbose npm  v6.4.1
121 error Error while executing:
121 error /usr/bin/git ls-remote -h -t git://github.com/jwarby/i18n-lint.git
121 error
121 error undefined
121 error exited with error code: 128
122 verbose exit [ 1, true ]
```

#### Expected behavior

npm install completes without errors

#### Actual behavior

Error is shown on console and logged to file and install process ends.

#### Steps to reproduce

```
$ git clone https://github.com/tellform/tellform.git
$ cd tellform
$ npm install
```

#### Environment

RedHat Enterprise Linux 7, node v6.14.4, npm v6.4.1. bower, grunt, grunt-cli, mongodb, redis installed as instructed.

**Comment by whitef0x0** [comment]
@mojontwins did you get it to work?

**Comment by mojontwins** [comment]
Yes, sorry. As soon as I added the issue, I was told that my company doesn't allow ssh connections outside the network, so that "git remote-ls" failed as it required accessing "git://github.com/..." and not "git://github.com/...". The walkaround was instructing git to replace "git://" by "https://":

```
git config --global url."https://github.com/".insteadOf "git://github.com/"
```
