### ISSUE TITLE
getting error when signup

### ISSUE THREAD

**Issue by sebastianxcf** [tellform/tellform#322]
#### What's this issue about?
When I try to signup a new user I'mgetting this error in the console : 

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at Object.randomBytes (internal/crypto/random.js:55:11)
    at Object.options.source (/home/scastellanos/tellform-code/tellform/node_modules/email-verification/node_modules/rand-token/index.js:60:25)

node --version
v10.1.0
npm --version
5.6.0

It's a bug related with the node version ?
Do I have to update something in the code ?
Best Regards,

**Comment by sebastianxcf** [comment]
Solved,
I had to install node version 8.12 and uṕdate vim package-lock.json 
"email-verification": {
      "version": "github:tellform/node-email-verification#8b179f34e0943c389b2058c9ec1e6d2135a72857",
      "requires": {
        "mongoose": "3.8.40",
        "nodemailer": "4.0.1",
        "rand-token": "0.4.0"
      },

Set rand-token to "0.4.0"
